### ISSUE TITLE
Starting many nodes at once throw exception address already in use

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube#92] opened 2016-09-21 15:39 UTC
Code: 

``` java
    for (int i = 0 ; i < 50; i++) {
      exec.execute(new Runnable() {
        @Override
        public void run() {
          ICluster member = Cluster.joinAwait(seed.address());
        }
      });
    }
```

Output:

```
I 0921-1835:43,635 i.s.t.Transport Connected from 10.150.4.21:4816 to 10.150.4.21:4807: [id: 0xa5f9fce7, L:/10.150.4.21:51671 - R:/10.150.4.21:4807] [sc-io-52-2]
D 0921-1835:43,667 i.s.c.m.MembershipProtocol Received membership gossip: {m: 6A97C20D04045F95A81A@10.150.4.21:4803, s: SUSPECT, inc: 0} [sc-membership-10.150.4.21:4801]
Exception in thread "pool-1-thread-8" java.lang.RuntimeException: java.net.BindException: Address already in use: bind
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at io.scalecube.cluster.Cluster.joinAwait(Cluster.java:94)
    at io.scalecube.leaderelection.LeaderElectionIT$1.run(LeaderElectionIT.java:97)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.net.BindException: Address already in use: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
    at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:501)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1218)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:505)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:490)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:965)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:210)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:402)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
    ... 1 more
```

**Comment by antonkharenko** [comment] 2016-09-21 16:31
It is doing check that port is available and if yes bind to this port, but since there 50 nodes doing it in parallel there is a race condition between the check and binding. 

For test purpose I recommend to either start each node on specific port or at least configure starting port different for each node in order to avoid contention for the ports at all. 

Here is a transport config example how to start each node on different fixed port:

``` java
TransportConfig conf = TransportConfig.builder()
  .port(TransportConfig.DEFAULT_PORT + nodeIndex)
  .portAutoIncrement(false)
  .build()
```

**Comment by ronenhamias** [comment] 2016-09-21 18:57
i understand there are ways to workaround this issue but i think that its better to locate port until success
users might fall on taken ports even if they are not taken by cluster code it self and still would like to start a node successfully - not only because of this specific case but also by the desire to run several nodes under same container or just by mistake try to connect on already used port.

**Comment by antonkharenko** [comment] 2016-09-21 19:08
Just for clarity, if you try to connect on already used port it will not fail with port already used exception since it will select next available one, the issue is specific for the case when you start many processes at same moment of time and all of them trying to bind for the same port.

**Comment by ronenhamias** [comment] 2016-09-21 19:11
ok so can it be same situation that someone take my port at this exact moment of time?
my process starts and someone take the port... is it really matters who?

**Comment by antonkharenko** [comment] 2016-09-21 19:16
It's possible only in case if they start practically in the same moment of time like in the range of some nano seconds or so.

**Comment by ronenhamias** [comment] 2016-09-21 19:20
yep - exactly.
so need to fail-over and not fail

**Comment by antonkharenko** [comment] 2016-09-21 19:33
Yes, but it's practically impossible outside of the code snippet above where you start several nodes in the for-loop.

**Comment by ronenhamias** [comment] 2016-09-21 19:35
i didnt understand why its not possible
i start just one node and someone in some rare moment of time just take this port...

**Comment by antonkharenko** [comment] 2016-12-06 18:04
Fixed in PR: https://github.com/scalecube/scalecube/pull/117

**Closed by antonkharenko** 2016-12-06 18:04 UTC
Labels: cluster, defect
