### ISSUE TITLE
Observable support for multiple clients

### ISSUE THREAD

**Issue by segabriel** [scalecube/scalecube#291] opened 2018-05-06 08:20 UTC
For now, Observable doesn't work correctly for multiple clients.
For example, some service:

    @Service
    public interface Generator {
        @ServiceMethod
        Observable<Response> generate();
  
        class Response {
          public String data;
  
          public Response(String data) {
            this.data = data;
          }
  
          public String getData() {
            return data;
          }
  
          public void setData(String data) {
            this.data = data;
          }
        }
    }

its implementation:

    public class SimpleGenerator implements Generator {
    
      private AtomicInteger sub = new AtomicInteger();
    
        @Override
        public Observable<Response> generate() {
          AtomicInteger i = new AtomicInteger();
          int sub = this.sub.incrementAndGet();
          return Observable.interval(1, TimeUnit.SECONDS).map(s -> new Response(sub + " => " + i.incrementAndGet()));
        }
    }

and test:

    public class MultiClientTest {
    
      public static void main(String[] args) throws InterruptedException {
        Microservices gateway = Microservices.builder()
            .build();
    
        Microservices node = Microservices.builder()
            .seeds(gateway.cluster().address())
            .services(new SimpleGenerator())
            .build();
    
        Generator service = gateway.proxy().api(Generator.class).create();
    
        service.generate().subscribe(r -> System.out.println("s1: " + r.data));
        service.generate().subscribe(r -> System.err.println("s2: " + r.data));
    
        TimeUnit.SECONDS.sleep(5);
      }
    }

it duplicates response for all clients, its ouptut following:

      s1: 1 => 1
      s1: 2 => 1
      s2: 1 => 1
      s2: 2 => 1
      s1: 1 => 2
      s1: 2 => 2
      s2: 1 => 2
      s2: 2 => 2
      s2: 1 => 3
      s1: 1 => 3
      s1: 2 => 3
      s2: 2 => 3
      s2: 1 => 4
      s1: 1 => 4
      s1: 2 => 4
      s2: 2 => 4

Good news, I have tested https://github.com/scalecube/scalecube-services
And all works there

    @Service
    public interface Generator {
        @ServiceMethod
        Flux<String> generate();
    }

    public class SimpleGenerator implements Generator {
      private AtomicInteger sub = new AtomicInteger();
    
        @Override
        public Flux<String> generate() {
          AtomicInteger i = new AtomicInteger();
          int sub = this.sub.incrementAndGet();
          return Flux.interval(Duration.ofSeconds(1)).map(s -> sub + " => " + i.incrementAndGet());
        }
    }

    public class MultiClientTest {
    
        public static void main(String[] args) throws InterruptedException {
            Microservices gateway = Microservices.builder()
                    .build();
    
            Microservices node = Microservices.builder()
                    .seeds(gateway.cluster().address())
                    .services(new SimpleGenerator())
                    .build();
    
            Generator service = gateway.call().api(Generator.class);
    
            service.generate().subscribe(r -> System.out.println("s1: " + r));
            service.generate().subscribe(r -> System.err.println("s2: " + r));
    
            TimeUnit.SECONDS.sleep(5);
        }
    }

it output following:

    s2: 1 => 1
    s1: 2 => 1
    s2: 1 => 2
    s1: 2 => 2
    s2: 1 => 3
    s1: 2 => 3
    s1: 2 => 4
    s2: 1 => 4
    s2: 1 => 5
    s1: 2 => 5

**Comment by rasentry** [comment] 2018-05-08 17:19
I thing it is duplicate of #289

**Comment by ronenhamias** [comment] 2018-05-10 05:34
https://github.com/scalecube/scalecube/pull/292

**Closed** 2018-05-10 19:25 UTC
