### ISSUE TITLE
could not emit value due to lack of requests

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube#94] opened 2016-09-21 18:52 UTC
D 0921-2012:52,361 i.s.c.m.MembershipProtocol Received membership gossip: {m: B1F8BFB1348E14961D43@192.168.56.1:4806, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: CAE02455F999E2922CD0@192.168.56.1:4833, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: F9CFDD6BBCDA0D3501DE@192.168.56.1:4824, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: C766652671112FF1C5EE@192.168.56.1:4808, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: EB953B6C61C469DEF806@192.168.56.1:4810, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 66488847A1EDA50347C9@192.168.56.1:4832, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 19A8DE155A84384FD291@192.168.56.1:4829, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
Caused by: rx.exceptions.OnErrorNotImplementedException: PublishSubject: could not emit value due to lack of requestsD 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: B7E91373CFA1F3EE0114@192.168.56.1:4822, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]

D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 1A3B80478AAA6B1C4D08@192.168.56.1:4811, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
	at rx.observers.Subscribers$2.onError(Subscribers.java:98)D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 3E6E3B7E728216983758@192.168.56.1:4819, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: D84132475706BF50DB84@192.168.56.1:4805, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 463252533764270DD522@192.168.56.1:4826, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 56A9D62FA225C77E0775@192.168.56.1:4812, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: D51EDA984103D2127931@192.168.56.1:4807, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4810]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 670A22E1FB0738308DBF@192.168.56.1:4815, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]

	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 26F63679B615DA669958@192.168.56.1:4802, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]

	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 20CBEF63348DDFA5914C@192.168.56.1:4809, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onError(OnSubscribeFilter.java:90)
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: CEFBE7DB34215A903F0E@192.168.56.1:4823, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:276)
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: B12B8359EC6CF45448FC@192.168.56.1:4825, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 70DE453E2F3CDA46386A@192.168.56.1:4816, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 8 more
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 541CF59CB5D7600987B2@192.168.56.1:4835, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 06F38D0850CA8CA28640@192.168.56.1:4818, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
Caused by: rx.exceptions.MissingBackpressureException: PublishSubject: could not emit value due to lack of requests
D 0921-2012:52,366 i.s.c.m.MembershipProtocol Received membership gossip: {m: CF4514CF9004168E6749@192.168.56.1:4828, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4811]
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:308)D 0921-2012:52,362 i.s.l.RaftLeaderElection Received RAFT_HEARTBEAT[sc/raft/heartbeat] from 192.168.56.1:4801 [sc-leaderelection-192.168.56.1:4810]

D 0921-2012:52,362 i.s.c.m.MembershipProtocol Received membership gossip: {m: 8A93E617202E913A9F20@192.168.56.1:4814, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4810]
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:220)D 0921-2012:52,368 i.s.l.RaftLeaderElection FOLLOWER Node: 192.168.56.1:4810 received heartbeat from  192.168.56.1:4801 [sc-leaderelection-192.168.56.1:4810]

	at rx.subjects.PublishSubject.onNext(PublishSubject.java:73)
	at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
	at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:67)
	at io.scalecube.cluster.gossip.GossipProtocol.onGossipReq(GossipProtocol.java:208)
D 0921-2012:52,368 i.s.c.m.MembershipProtocol Received membership gossip: {m: 05D6D0D4CDE127C6D27F@192.168.56.1:4820, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4810]
	at rx.observers.Subscribers$2.onNext(Subscribers.java:103)
D 0921-2012:52,368 i.s.c.m.MembershipProtocol Received membership gossip: {m: 5707AA2EA0268C8AE9D7@192.168.56.1:4821, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4810]
D 0921-2012:52,368 i.s.c.m.MembershipProtocol Received membership gossip: {m: 07AF79CF5BB684F9E3CF@192.168.56.1:4834, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4810]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
	... 9 more
D 0921-2012:52,368 i.s.c.m.MembershipProtocol Received membership gossip: {m: D1EE4899E5641E60E1BF@192.168.56.1:4831, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4810]
D 0921-2012:52,368 i.s.c.m.MembershipProtocol Received membership gossip: {m: 7261B040D4BFC3486385@192.168.56.1:4804, s: ALIVE, inc: 0} [sc-membership-192.168.56.1:4810]
D 0921-2012:52,368 i.s.c.m.MembershipProtocol Received membership gossip: {m: A2E747DF9F029477CD1E@192.1

**Comment by antonkharenko** [comment] 2016-09-21 18:58
Duplicate of https://github.com/scalecube/scalecube/issues/93

**Closed by antonkharenko** 2016-09-21 18:58 UTC
Labels: cluster, defect, duplicate
