### ISSUE TITLE
Binding transport to IPv6 address causes IllegalFormatConversionException

### ISSUE THREAD

**Issue by guss77** [scalecube/scalecube#171] opened 2017-01-15 11:17 UTC
When starting Scalecube and one of the addresses only has an IPv6 address (for various reasons, in my case the DHCP didn't complete, but we could really be using only an IPv6 network) then `Addressing` uses `NetworkInterface.getInetAddresses()` to get an `Inet6Address` which looks something like this: `/fe80:0:0:0:8cf6:f5c8:c946:2c30%eno1`.

Then when `MembershipProtocol` constructor tries to use the address to create a "name format" for `ThreadFactoryBuilder`, the `%` in the address causes the thread factory builder to crash with a `java.util.IllegalFormatConversionException` when it tries to create thread names using `String.format()`.

The full stack trace looks like this:

```
java.util.IllegalFormatConversionException: e != java.lang.Integer
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
	at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2806)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2753)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2981)
	at com.google.common.util.concurrent.ThreadFactoryBuilder.format(ThreadFactoryBuilder.java:181)
	at com.google.common.util.concurrent.ThreadFactoryBuilder.setNameFormat(ThreadFactoryBuilder.java:70)
	at io.scalecube.cluster.membership.MembershipProtocol.<init>(MembershipProtocol.java:110)
	at io.scalecube.cluster.ClusterImpl.lambda$join0$25(ClusterImpl.java:81)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.scalecube.transport.TransportImpl.lambda$bind0$0(TransportImpl.java:104)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:897)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:570)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:511)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:496)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:363)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

Using scalecube-cluster-1.0.3

**Comment by ronenhamias** [comment] 2017-01-15 11:23
thanks for the contribution by reporting this issue

**Comment by ronenhamias** [comment] 2017-01-15 11:36
i was able to reproduce the issue with the simple example
 Address address = Address.create("/fe80:0:0:0:8cf6:f5c8:c946:2c30%eno1", 4001);
    String nameFormat = "sc-membership-" + address.toString();
    Executors.newSingleThreadScheduledExecutor(
        new ThreadFactoryBuilder().setNameFormat(nameFormat).setDaemon(true).build());

possible solution is to normalize the name by replacing the Illegal char as following:
Address address = Address.create("/fe80:0:0:0:8cf6:f5c8:c946:2c30%eno1", 4001);
    String nameFormat = "sc-membership-" + address.toString().replaceAll("%", "-");
    Executors.newSingleThreadScheduledExecutor(
        new ThreadFactoryBuilder().setNameFormat(nameFormat).setDaemon(true).build());

**Comment by guss77** [comment] 2017-01-15 11:40
Maybe you want to just "escape" the `nameFormat` for `String.format()` using `replaceAll("%","%%")`.

**Comment by ronenhamias** [comment] 2017-01-15 11:41
created a pull request
https://github.com/scalecube/scalecube/pull/172

**Comment by ronenhamias** [comment] 2017-01-15 11:42
i kind of did the same and added unit test to cover this case
let me know if this can work for you.

**Comment by ronenhamias** [comment] 2017-01-15 13:18
pull request https://github.com/scalecube/scalecube/pull/172

**Comment by guss77** [comment] 2017-01-15 15:45
#172 indeed fixes the specific stack trace I reported above, but there are other places that use an address in a `ThreadFactoryBuilder` and all suffer from the same problem, so now that `MembershipProtocol` don't crash, the others do :-/

Here is my results from grepping for candidates:

```
io.scalecube.cluster.fdetector.FailureDetector
io.scalecube.cluster.gossip.GossipProtocol
```

A. Maybe the fix should be in `Address.toString()` or add an `Address.toTemplate(String prefix)` implementation - otherwise the code starting to look not-DRY.
B. Again I recommend using `%%` as the substitution string instead of `-` as that, IMHO, is a better semantic - it doesn't hide the fact that Java uses `%<if-name>` in IPv6 suffixes.

**Comment by ronenhamias** [comment] 2017-01-15 16:07
thanks again :)

+1 to %%

i think the fix should not be in the toString() as the issue is only when creating nameFormat.

so either we fix it in all the places or we create some utility function to create nameFormat.

i changed the pull request according to your imput so:
there is a thread factory used in transport layer so services can reuse this thread factory
the normalization of the name format is done in one place.

**Comment by antonkharenko** [comment] 2017-01-16 20:48
Fixed by https://github.com/scalecube/scalecube/pull/173

**Closed by antonkharenko** 2017-01-16 20:48 UTC
Labels: cluster, defect

**Comment by ronenhamias** [comment] 2017-01-16 22:16
@guss77 and @antonkharenko thanks for your contribution!
